//! Built-in alias suggestions (same list as the desktop app).

pub struct Suggestion {
    pub name: &'static str,
    pub path: &'static str,
    pub action: &'static str,
    pub custom_command: &'static str,
    pub description: &'static str,
}

pub const SUGGESTIONS: &[Suggestion] = &[
    Suggestion {
        name: "gs",
        path: "",
        action: "custom",
        custom_command: "git status --short --branch",
        description: "Compact Git status",
    },
    Suggestion {
        name: "gaa",
        path: "",
        action: "custom",
        custom_command: "git add --all",
        description: "Stage all Git changes",
    },
    Suggestion {
        name: "gc",
        path: "",
        action: "custom",
        custom_command: "git commit %*",
        description: "Create a Git commit",
    },
    Suggestion {
        name: "gcm",
        path: "",
        action: "custom",
        custom_command: "git commit -m \"%*\"",
        description: "Commit with a message",
    },
    Suggestion {
        name: "gp",
        path: "",
        action: "custom",
        custom_command: "git push %*",
        description: "Push the current branch",
    },
    Suggestion {
        name: "gpl",
        path: "",
        action: "custom",
        custom_command: "git pull --rebase",
        description: "Pull with rebase",
    },
    Suggestion {
        name: "gb",
        path: "",
        action: "custom",
        custom_command: "git branch",
        description: "List local Git branches",
    },
    Suggestion {
        name: "gsw",
        path: "",
        action: "custom",
        custom_command: "git switch %*",
        description: "Switch Git branches",
    },
    Suggestion {
        name: "gd",
        path: "",
        action: "custom",
        custom_command: "git diff",
        description: "Show unstaged changes",
    },
    Suggestion {
        name: "gds",
        path: "",
        action: "custom",
        custom_command: "git diff --staged",
        description: "Show staged changes",
    },
    Suggestion {
        name: "glog",
        path: "",
        action: "custom",
        custom_command: "git log --oneline --graph --decorate --all",
        description: "Compact Git history graph",
    },
    Suggestion {
        name: "gstash",
        path: "",
        action: "custom",
        custom_command: "git stash push %*",
        description: "Stash current changes",
    },
    Suggestion {
        name: "dcu",
        path: "",
        action: "custom",
        custom_command: "docker compose up -d",
        description: "Start Docker Compose",
    },
    Suggestion {
        name: "dcd",
        path: "",
        action: "custom",
        custom_command: "docker compose down",
        description: "Stop Docker Compose",
    },
    Suggestion {
        name: "dcl",
        path: "",
        action: "custom",
        custom_command: "docker compose logs -f %*",
        description: "Follow Compose logs",
    },
    Suggestion {
        name: "dcb",
        path: "",
        action: "custom",
        custom_command: "docker compose build %*",
        description: "Build Compose services",
    },
    Suggestion {
        name: "dcr",
        path: "",
        action: "custom",
        custom_command: "docker compose restart %*",
        description: "Restart Compose services",
    },
    Suggestion {
        name: "dps",
        path: "",
        action: "custom",
        custom_command: "docker ps",
        description: "List running containers",
    },
    Suggestion {
        name: "di",
        path: "",
        action: "custom",
        custom_command: "docker images",
        description: "List local Docker images",
    },
    Suggestion {
        name: "ddf",
        path: "",
        action: "custom",
        custom_command: "docker system df",
        description: "Show Docker disk usage",
    },
    Suggestion {
        name: "dex",
        path: "",
        action: "custom",
        custom_command: "docker exec -it %*",
        description: "Run a command in a container",
    },
    Suggestion {
        name: "gw",
        path: "",
        action: "custom",
        custom_command: "call gradlew.bat %*",
        description: "Run the Gradle wrapper",
    },
    Suggestion {
        name: "gwb",
        path: "",
        action: "custom",
        custom_command: "call gradlew.bat build",
        description: "Build with Gradle wrapper",
    },
    Suggestion {
        name: "gwtest",
        path: "",
        action: "custom",
        custom_command: "call gradlew.bat test",
        description: "Run Gradle tests",
    },
    Suggestion {
        name: "mw",
        path: "",
        action: "custom",
        custom_command: "call mvnw.cmd %*",
        description: "Run the Maven wrapper",
    },
    Suggestion {
        name: "mvnb",
        path: "",
        action: "custom",
        custom_command: "call mvnw.cmd clean package",
        description: "Build with Maven wrapper",
    },
    Suggestion {
        name: "mvnt",
        path: "",
        action: "custom",
        custom_command: "call mvnw.cmd test",
        description: "Run Maven tests",
    },
    Suggestion {
        name: "ni",
        path: "",
        action: "custom",
        custom_command: "call npm install",
        description: "Install npm dependencies",
    },
    Suggestion {
        name: "nrd",
        path: "",
        action: "custom",
        custom_command: "call npm run dev",
        description: "Start the npm dev script",
    },
    Suggestion {
        name: "nrb",
        path: "",
        action: "custom",
        custom_command: "call npm run build",
        description: "Run the npm build script",
    },
    Suggestion {
        name: "ll",
        path: "",
        action: "custom",
        custom_command: "dir /a",
        description: "Detailed file list",
    },
    Suggestion {
        name: "c",
        path: "",
        action: "custom",
        custom_command: "cls",
        description: "Clear the terminal",
    },
    Suggestion {
        name: "serve",
        path: "",
        action: "custom",
        custom_command: "python -m http.server",
        description: "Serve the current folder",
    },
    Suggestion {
        name: "ports",
        path: "",
        action: "custom",
        custom_command: "netstat -ano | findstr LISTENING",
        description: "Show listening TCP ports",
    },
    Suggestion {
        name: "downloads",
        path: "~/Downloads",
        action: "navigate",
        custom_command: "",
        description: "Jump to Downloads",
    },
    Suggestion {
        name: "home",
        path: "~",
        action: "open",
        custom_command: "",
        description: "Open your home folder",
    },
];
