use serde::{Deserialize, Serialize};
use std::{env, fs, path::PathBuf};

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
struct AliasEntry {
    id: String,
    name: String,
    path: String,
    action: String,
    custom_command: Option<String>,
    command_preview: String,
    created_at: String,
    updated_at: String,
}

#[derive(Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
struct AppState {
    aliases: Vec<AliasEntry>,
    config_file: String,
    aliases_file: String,
    source_line: String,
    zshrc_source_present: bool,
}

const SOURCE_LINE: &str = "source ~/.easyalias/aliases.zsh";

fn home_dir() -> Result<PathBuf, String> {
    env::var_os("HOME")
        .map(PathBuf::from)
        .ok_or_else(|| "HOME konnte nicht gelesen werden.".to_string())
}

fn app_dir() -> Result<PathBuf, String> {
    Ok(home_dir()?.join(".easyalias"))
}

fn config_file() -> Result<PathBuf, String> {
    Ok(app_dir()?.join("config.json"))
}

fn aliases_file() -> Result<PathBuf, String> {
    Ok(app_dir()?.join("aliases.zsh"))
}

fn zshrc_file() -> Result<PathBuf, String> {
    Ok(home_dir()?.join(".zshrc"))
}

fn zshrc_source_present() -> bool {
    zshrc_file()
        .ok()
        .and_then(|path| fs::read_to_string(path).ok())
        .map(|content| content.lines().any(|line| line.trim() == SOURCE_LINE))
        .unwrap_or(false)
}

fn display_home_path(path: PathBuf) -> Result<String, String> {
    let home = home_dir()?;
    if let Ok(stripped) = path.strip_prefix(&home) {
        return Ok(format!("~/{}", stripped.display()));
    }

    Ok(path.display().to_string())
}

fn validate_alias_name(name: &str) -> bool {
    let mut chars = name.chars();
    let Some(first) = chars.next() else {
        return false;
    };

    if !(first.is_ascii_alphabetic() || first == '_') {
        return false;
    }

    chars.all(|char| char.is_ascii_alphanumeric() || char == '_' || char == '-')
}

fn single_quote(value: &str) -> String {
    format!("'{}'", value.replace('\'', "'\\''"))
}

fn render_aliases(aliases: &[AliasEntry]) -> Result<String, String> {
    let mut lines = vec![
        "# Generated by EasyAlias.".to_string(),
        "# Edit aliases in the app, not by hand.".to_string(),
        String::new(),
    ];

    for alias in aliases {
        if !validate_alias_name(&alias.name) {
            return Err(format!("Ungueltiger Alias-Name: {}", alias.name));
        }

        if alias.command_preview.trim().is_empty() {
            return Err(format!("Alias {} hat keinen Befehl.", alias.name));
        }

        lines.push(format!(
            "alias {}={}",
            alias.name,
            single_quote(&alias.command_preview)
        ));
    }

    Ok(format!("{}\n", lines.join("\n")))
}

fn app_state(aliases: Vec<AliasEntry>) -> Result<AppState, String> {
    Ok(AppState {
        aliases,
        config_file: display_home_path(config_file()?)?,
        aliases_file: display_home_path(aliases_file()?)?,
        source_line: SOURCE_LINE.to_string(),
        zshrc_source_present: zshrc_source_present(),
    })
}

#[tauri::command]
fn load_aliases() -> Result<AppState, String> {
    let path = config_file()?;

    if !path.exists() {
        return app_state(Vec::new());
    }

    let content = fs::read_to_string(&path)
        .map_err(|error| format!("{} konnte nicht gelesen werden: {}", path.display(), error))?;

    let aliases = serde_json::from_str::<Vec<AliasEntry>>(&content)
        .map_err(|error| format!("config.json ist kein gueltiges Alias-JSON: {}", error))?;

    app_state(aliases)
}

#[tauri::command]
fn save_aliases(aliases: Vec<AliasEntry>) -> Result<AppState, String> {
    let directory = app_dir()?;
    fs::create_dir_all(&directory)
        .map_err(|error| format!("{} konnte nicht erstellt werden: {}", directory.display(), error))?;

    let config = serde_json::to_string_pretty(&aliases)
        .map_err(|error| format!("Aliase konnten nicht serialisiert werden: {}", error))?;
    let aliases_zsh = render_aliases(&aliases)?;

    let config_path = config_file()?;
    let aliases_path = aliases_file()?;

    fs::write(&config_path, format!("{}\n", config))
        .map_err(|error| format!("{} konnte nicht geschrieben werden: {}", config_path.display(), error))?;
    fs::write(&aliases_path, aliases_zsh)
        .map_err(|error| format!("{} konnte nicht geschrieben werden: {}", aliases_path.display(), error))?;

    app_state(aliases)
}

fn main() {
    tauri::Builder::default()
        .invoke_handler(tauri::generate_handler![load_aliases, save_aliases])
        .run(tauri::generate_context!())
        .expect("error while running EasyAlias");
}
