import "./styles.css";

type AliasAction =
  | "navigate"
  | "open"
  | "execute"
  | "compile_gradle"
  | "compile_maven"
  | "custom";

type AliasEntry = {
  id: string;
  name: string;
  path: string;
  action: AliasAction;
  customCommand?: string;
  commandPreview: string;
  createdAt: string;
  updatedAt: string;
};

type AppState = {
  aliases: AliasEntry[];
  configFile: string;
  aliasesFile: string;
  sourceLine: string;
  zshrcSourcePresent: boolean;
};

type AliasForm = {
  id?: string;
  name: string;
  path: string;
  action: AliasAction;
  customCommand: string;
};

const actionLabels: Record<AliasAction, string> = {
  navigate: "Navigiere zu Ordner",
  open: "Öffnen",
  execute: "Ausführen",
  compile_gradle: "Gradle Build",
  compile_maven: "Maven Build",
  custom: "Custom Command"
};

const emptyForm: AliasForm = {
  name: "",
  path: "",
  action: "navigate",
  customCommand: ""
};

let appState: AppState = {
  aliases: [],
  configFile: "~/.easyalias/config.json",
  aliasesFile: "~/.easyalias/aliases.zsh",
  sourceLine: "source ~/.easyalias/aliases.zsh",
  zshrcSourcePresent: false
};

let form: AliasForm = { ...emptyForm };
let selectedId: string | null = null;
let notice = "";
let error = "";

const app = document.querySelector<HTMLDivElement>("#app");

if (!app) {
  throw new Error("App container not found");
}

const appElement = app;

function isTauriRuntime() {
  return "__TAURI_INTERNALS__" in window;
}

async function invokeCommand<T>(command: string, args?: Record<string, unknown>): Promise<T> {
  const { invoke } = await import("@tauri-apps/api/core");
  return invoke<T>(command, args);
}

function createId() {
  if ("crypto" in window && "randomUUID" in crypto) {
    return crypto.randomUUID();
  }

  return `alias_${Date.now()}_${Math.random().toString(16).slice(2)}`;
}

function nowIso() {
  return new Date().toISOString();
}

function shellPath(path: string) {
  const trimmed = path.trim();
  if (!trimmed) return "";

  if (trimmed === "~") return '"$HOME"';
  if (trimmed.startsWith("~/")) {
    return `"$HOME/${escapeDoubleQuoted(trimmed.slice(2))}"`;
  }

  return `"${escapeDoubleQuoted(trimmed)}"`;
}

function escapeDoubleQuoted(value: string) {
  return value.replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/`/g, "\\`").replace(/\$/g, "\\$");
}

function buildCommandPreview(entry: Pick<AliasEntry, "path" | "action" | "customCommand">) {
  const path = shellPath(entry.path);

  switch (entry.action) {
    case "navigate":
      return path ? `cd ${path}` : "";
    case "open":
      return path ? `open ${path}` : "";
    case "execute":
      return path;
    case "compile_gradle":
      return path ? `cd ${path} && ./gradlew build` : "";
    case "compile_maven":
      return path ? `cd ${path} && mvn clean package` : "";
    case "custom":
      return entry.customCommand?.trim() ?? "";
  }
}

function validateAlias(formValue: AliasForm) {
  if (!/^[A-Za-z_][A-Za-z0-9_-]*$/.test(formValue.name.trim())) {
    return "Alias-Name muss mit Buchstabe oder _ starten und darf nur Buchstaben, Zahlen, _ oder - enthalten.";
  }

  if (formValue.action === "custom") {
    if (!formValue.customCommand.trim()) return "Custom Command darf nicht leer sein.";
    return "";
  }

  if (!formValue.path.trim()) return "Bitte einen Pfad oder Befehl eintragen.";

  return "";
}

function renderAliasLine(alias: AliasEntry) {
  const escaped = alias.commandPreview.replace(/'/g, "'\\''");
  return `alias ${alias.name}='${escaped}'`;
}

function renderAliasesZsh(aliases: AliasEntry[]) {
  const lines = [
    "# Generated by EasyAlias.",
    "# Edit aliases in the app, not by hand.",
    "",
    ...aliases.map(renderAliasLine)
  ];

  return `${lines.join("\n")}\n`;
}

async function loadState() {
  clearMessages();

  if (isTauriRuntime()) {
    try {
      appState = await invokeCommand<AppState>("load_aliases");
      render();
      return;
    } catch (loadError) {
      error = String(loadError);
    }
  }

  const saved = localStorage.getItem("easyalias-state");
  if (saved) {
    appState = JSON.parse(saved) as AppState;
  }

  render();
}

async function saveState() {
  clearMessages();

  const aliases = [...appState.aliases].sort((a, b) => a.name.localeCompare(b.name));

  if (isTauriRuntime()) {
    try {
      appState = await invokeCommand<AppState>("save_aliases", { aliases });
      notice = `Gespeichert: ${appState.aliasesFile}`;
      render();
      return;
    } catch (saveError) {
      error = String(saveError);
      render();
      return;
    }
  }

  appState = { ...appState, aliases };
  localStorage.setItem("easyalias-state", JSON.stringify(appState));
  notice = "Browser-Vorschau gespeichert. In Tauri schreibt die App echte Dateien.";
  render();
}

function clearMessages() {
  notice = "";
  error = "";
}

function resetForm() {
  form = { ...emptyForm };
  selectedId = null;
  clearMessages();
  render();
}

function selectAlias(id: string) {
  const alias = appState.aliases.find((item) => item.id === id);
  if (!alias) return;

  selectedId = id;
  form = {
    id: alias.id,
    name: alias.name,
    path: alias.path,
    action: alias.action,
    customCommand: alias.customCommand ?? ""
  };
  clearMessages();
  render();
}

async function upsertAlias(event: SubmitEvent) {
  event.preventDefault();
  clearMessages();

  const validationError = validateAlias(form);
  if (validationError) {
    error = validationError;
    render();
    return;
  }

  const duplicate = appState.aliases.find(
    (alias) => alias.name === form.name.trim() && alias.id !== selectedId
  );

  if (duplicate) {
    error = `Alias "${form.name.trim()}" gibt es schon.`;
    render();
    return;
  }

  const existing = selectedId ? appState.aliases.find((alias) => alias.id === selectedId) : undefined;
  const timestamp = nowIso();
  const nextAlias: AliasEntry = {
    id: existing?.id ?? createId(),
    name: form.name.trim(),
    path: form.path.trim(),
    action: form.action,
    customCommand: form.action === "custom" ? form.customCommand.trim() : undefined,
    commandPreview: buildCommandPreview(form),
    createdAt: existing?.createdAt ?? timestamp,
    updatedAt: timestamp
  };

  appState = {
    ...appState,
    aliases: existing
      ? appState.aliases.map((alias) => (alias.id === existing.id ? nextAlias : alias))
      : [...appState.aliases, nextAlias]
  };

  form = { ...emptyForm };
  selectedId = null;
  await saveState();
}

async function deleteAlias(id: string) {
  appState = {
    ...appState,
    aliases: appState.aliases.filter((alias) => alias.id !== id)
  };

  if (selectedId === id) {
    form = { ...emptyForm };
    selectedId = null;
  }

  await saveState();
}

function updateForm<K extends keyof AliasForm>(key: K, value: AliasForm[K]) {
  form = { ...form, [key]: value };
  clearMessages();
  render();
}

function formatDate(value: string) {
  return new Intl.DateTimeFormat("de-DE", {
    dateStyle: "medium",
    timeStyle: "short"
  }).format(new Date(value));
}

function formPreview() {
  return buildCommandPreview(form) || "Noch kein Befehl generiert";
}

function render() {
  const aliases = [...appState.aliases].sort((a, b) => a.name.localeCompare(b.name));

  appElement.innerHTML = `
    <section class="shell">
      <header class="topbar">
        <div>
          <p class="eyebrow">macOS Alias Manager</p>
          <h1>EasyAlias</h1>
        </div>
        <button class="ghost-button" data-action="reset">Neu</button>
      </header>

      <section class="status-grid">
        <div>
          <span>Alias-Datei</span>
          <strong>${appState.aliasesFile}</strong>
        </div>
        <div>
          <span>.zshrc Source</span>
          <strong>${appState.zshrcSourcePresent ? "Verbunden" : "Noch einzutragen"}</strong>
        </div>
        <div>
          <span>Aliase</span>
          <strong>${aliases.length}</strong>
        </div>
      </section>

      ${
        appState.zshrcSourcePresent
          ? ""
          : `<aside class="source-hint">
              <span>Einmalig in ~/.zshrc einfügen:</span>
              <code>${appState.sourceLine}</code>
            </aside>`
      }

      ${notice ? `<p class="notice">${notice}</p>` : ""}
      ${error ? `<p class="error">${error}</p>` : ""}

      <section class="workspace">
        <form class="editor" id="alias-form">
          <div class="form-title">
            <h2>${selectedId ? "Alias bearbeiten" : "Alias erstellen"}</h2>
            <button class="primary-button" type="submit">${selectedId ? "Aktualisieren" : "Hinzufügen"}</button>
          </div>

          <label>
            Command Name
            <input name="name" value="${escapeHtml(form.name)}" placeholder="beerv2" autocomplete="off" />
          </label>

          <label>
            Ort / Datei / Befehl
            <input name="path" value="${escapeHtml(form.path)}" placeholder="~/Desktop/projekte/beerv2_app" autocomplete="off" />
          </label>

          <label>
            Aktion
            <select name="action">
              ${Object.entries(actionLabels)
                .map(
                  ([value, label]) =>
                    `<option value="${value}" ${form.action === value ? "selected" : ""}>${label}</option>`
                )
                .join("")}
            </select>
          </label>

          ${
            form.action === "custom"
              ? `<label>
                  Custom Command
                  <textarea name="customCommand" rows="4" placeholder='cd "$HOME/project" && ./run.sh'>${escapeHtml(form.customCommand)}</textarea>
                </label>`
              : ""
          }

          <div class="preview">
            <span>Vorschau</span>
            <code>${escapeHtml(formPreview())}</code>
          </div>
        </form>

        <section class="list" aria-label="Aliase">
          <div class="list-header">
            <h2>Deine Aliase</h2>
            <span>${aliases.length} Einträge</span>
          </div>

          ${
            aliases.length
              ? aliases
                  .map(
                    (alias) => `
                      <article class="alias-row ${alias.id === selectedId ? "selected" : ""}">
                        <button class="row-main" data-action="select" data-id="${alias.id}">
                          <span class="alias-name">${alias.name}</span>
                          <span class="alias-action">${actionLabels[alias.action]}</span>
                          <code>${escapeHtml(alias.commandPreview)}</code>
                          <span class="created">Erstellt ${formatDate(alias.createdAt)}</span>
                        </button>
                        <button class="icon-button" title="Löschen" data-action="delete" data-id="${alias.id}">×</button>
                      </article>
                    `
                  )
                  .join("")
              : `<div class="empty-state">
                  <strong>Noch keine Aliase</strong>
                  <span>Leg links deinen ersten Command an.</span>
                </div>`
          }
        </section>
      </section>

      <details class="generated">
        <summary>Generierte aliases.zsh anzeigen</summary>
        <pre>${escapeHtml(renderAliasesZsh(aliases))}</pre>
      </details>
    </section>
  `;

  bindEvents();
}

function bindEvents() {
  document.querySelector<HTMLFormElement>("#alias-form")?.addEventListener("submit", upsertAlias);

  document.querySelector<HTMLInputElement>('input[name="name"]')?.addEventListener("input", (event) => {
    updateForm("name", (event.target as HTMLInputElement).value);
  });

  document.querySelector<HTMLInputElement>('input[name="path"]')?.addEventListener("input", (event) => {
    updateForm("path", (event.target as HTMLInputElement).value);
  });

  document.querySelector<HTMLSelectElement>('select[name="action"]')?.addEventListener("change", (event) => {
    updateForm("action", (event.target as HTMLSelectElement).value as AliasAction);
  });

  document.querySelector<HTMLTextAreaElement>('textarea[name="customCommand"]')?.addEventListener("input", (event) => {
    updateForm("customCommand", (event.target as HTMLTextAreaElement).value);
  });

  document.querySelectorAll<HTMLButtonElement>("[data-action]").forEach((button) => {
    button.addEventListener("click", () => {
      const action = button.dataset.action;
      const id = button.dataset.id;

      if (action === "reset") resetForm();
      if (action === "select" && id) selectAlias(id);
      if (action === "delete" && id) void deleteAlias(id);
    });
  });
}

function escapeHtml(value: string) {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}

void loadState();
